### PR TITLE
add home nav bar

### PR DESCRIPTION
**Pull request by lesliekimm**
@cmaher92 this was more along the lines of what i was thinking. @ajbraus mentioned in Issue #34. I think this is more along the lines of what a new user would need. a home link towards the top.

### CODE REVIEW

**Comment by lesliekimm** [comment]
@cmaher92 this also gets rid of that weird margin at the top of the page content.

**Comment by lesliekimm** [comment]
also fixes issue #74 

started doing some random work on this branch so it does a couple things

**Comment by cmaher92** [comment]
- The nav bar is taking up 33% of my viewport, could we consider cutting that down? 
- The sticky header makes the navbar remain in view, I removed it earlier to allow for the content to be the focus. Is there an accessibility reason for keeping the header sticky?

**Comment by joshuarcher** [comment]
@cmaher92 @lesliekimm I think we could have the navbar at least shrink when scrolling down. It's definitely a little obtrusive. Cool logo 👍

**Comment by lesliekimm** [comment]
@joshuarcher @cmaher92 cool, i made the nav not fixed so it scrolls. look good otherwise?

**Comment by lesliekimm** [comment]
@cmaher92 no, there was no accessibility reason, i am just always viewing it on a larger screen so i hadn't thought of that issue.

**Comment by ajbraus** [comment]
I'm in agreement with @cmaher92 - @lesliekimm. The logo is too complex (mouse cursor, multiple "people icons", etc) Remember that these are NON TECHNICAL PEOPLE. They don't even know that those three "people icons" mean users. They probably don't even consider two blobs a person. That is learned behavior. 

Can we go back to just text and maybe a sub title that says what we actually are?

e.g. http://www.findmysit.com/ (this was a project I made a few weeks ago attempting to be as simple as possible. The navbar is very clear.

**Comment by lesliekimm** [comment]
@ajbraus okay cool, i think eventually even a simple logo will be better than just text, but we can go back to text for now. @cmaher92 will add those changes.

**Comment by joshuarcher** [comment]
@lesliekimm AWESOME

**Pull request merged**
